class BookingRequestModel {
  String status;
  BookingRequestResult data;
  String message;

  BookingRequestModel({
    required this.status,
    required this.data,
    required this.message,
  });

  factory BookingRequestModel.fromJson(Map<String, dynamic> json) => BookingRequestModel(
    status: json["status"],
    data: BookingRequestResult.fromJson(json["data"]),
    message: json["message"],
  );

  Map<String, dynamic> toJson() => {
    "status": status,
    "data": data.toJson(),
    "message": message,
  };
}

class BookingRequestResult {
  int id;
  String userId;
  String driverId;
  String driverIds;
  String picuplocation;
  String dropofflocation;
  String picuplat;
  String pickuplon;
  String droplat;
  String droplon;
  String sharerideType;
  String booktype;
  String carTypeId;
  String carSeats;
  String numberOfWitness;
  String bookedSeats;
  DateTime reqDatetime;
  String timezone;
  String picklatertime;
  DateTime picklaterdate;
  String routeImg;
  String startTime;
  String endTime;
  String wtStartTime;
  String wtEndTime;
  String waitingStatus;
  String acceptTime;
  int waitingCnt;
  String typeOfSigningId;
  String applyCode;
  String paymentType;
  String rideFare;
  String cardId;
  String status;
  String typeOfSigningName;
  String companyId;
  String numberOfSigning;
  String carTypeName;
  String realstateSigning;
  String realstateSettlement;
  String locationType;
  String name;
  String mobile;
  String email;
  String paymentStatus;
  String userRatingStatus;
  String uploadDocument;
  String emailtoprit;
  String scanandemail;
  String prepaid;
  String overnight;
  String stateName;
  String stateId;
  String nightCharge;
  String todayCharge;
  String noOfHours;
  String noOfDays;
  String bookBy;
  String operatorId;
  String signingCode;
  String notify;
  String cardSelectStatus;
  String cancelReaison;
  String rushCharge;
  String weekend;
  String witness;
  String express;
  int estimateTime;
  String estimateDistance;

  BookingRequestResult({
    required this.id,
    required this.userId,
    required this.driverId,
    required this.driverIds,
    required this.picuplocation,
    required this.dropofflocation,
    required this.picuplat,
    required this.pickuplon,
    required this.droplat,
    required this.droplon,
    required this.sharerideType,
    required this.booktype,
    required this.carTypeId,
    required this.carSeats,
    required this.numberOfWitness,
    required this.bookedSeats,
    required this.reqDatetime,
    required this.timezone,
    required this.picklatertime,
    required this.picklaterdate,
    required this.routeImg,
    required this.startTime,
    required this.endTime,
    required this.wtStartTime,
    required this.wtEndTime,
    required this.waitingStatus,
    required this.acceptTime,
    required this.waitingCnt,
    required this.typeOfSigningId,
    required this.applyCode,
    required this.paymentType,
    required this.rideFare,
    required this.cardId,
    required this.status,
    required this.typeOfSigningName,
    required this.companyId,
    required this.numberOfSigning,
    required this.carTypeName,
    required this.realstateSigning,
    required this.realstateSettlement,
    required this.locationType,
    required this.name,
    required this.mobile,
    required this.email,
    required this.paymentStatus,
    required this.userRatingStatus,
    required this.uploadDocument,
    required this.emailtoprit,
    required this.scanandemail,
    required this.prepaid,
    required this.overnight,
    required this.stateName,
    required this.stateId,
    required this.nightCharge,
    required this.todayCharge,
    required this.noOfHours,
    required this.noOfDays,
    required this.bookBy,
    required this.operatorId,
    required this.signingCode,
    required this.notify,
    required this.cardSelectStatus,
    required this.cancelReaison,
    required this.rushCharge,
    required this.weekend,
    required this.witness,
    required this.express,
    required this.estimateTime,
    required this.estimateDistance,
  });

  factory BookingRequestResult.fromJson(Map<String, dynamic> json) => BookingRequestResult(
    id: json["id"],
    userId: json["user_id"],
    driverId: json["driver_id"],
    driverIds: json["driver_ids"],
    picuplocation: json["picuplocation"],
    dropofflocation: json["dropofflocation"],
    picuplat: json["picuplat"],
    pickuplon: json["pickuplon"],
    droplat: json["droplat"],
    droplon: json["droplon"],
    sharerideType: json["shareride_type"],
    booktype: json["booktype"],
    carTypeId: json["car_type_id"],
    carSeats: json["car_seats"],
    numberOfWitness: json["number_of_witness"],
    bookedSeats: json["booked_seats"],
    reqDatetime: DateTime.parse(json["req_datetime"]),
    timezone: json["timezone"],
    picklatertime: json["picklatertime"],
    picklaterdate: DateTime.parse(json["picklaterdate"]),
    routeImg: json["route_img"],
    startTime: json["start_time"],
    endTime: json["end_time"],
    wtStartTime: json["wt_start_time"],
    wtEndTime: json["wt_end_time"],
    waitingStatus: json["waiting_status"],
    acceptTime: json["accept_time"],
    waitingCnt: json["waiting_cnt"],
    typeOfSigningId: json["type_of_signing_id"],
    applyCode: json["apply_code"],
    paymentType: json["payment_type"],
    rideFare: json["ride_fare"],
    cardId: json["card_id"],
    status: json["status"],
    typeOfSigningName: json["type_of_signing_name"],
    companyId: json["company_id"],
    numberOfSigning: json["number_of_signing"],
    carTypeName: json["car_type_name"],
    realstateSigning: json["realstate_signing"],
    realstateSettlement: json["realstate_settlement"],
    locationType: json["location_type"],
    name: json["name"],
    mobile: json["mobile"],
    email: json["email"],
    paymentStatus: json["payment_status"],
    userRatingStatus: json["user_rating_status"],
    uploadDocument: json["upload_document"],
    emailtoprit: json["emailtoprit"],
    scanandemail: json["scanandemail"],
    prepaid: json["prepaid"],
    overnight: json["overnight"],
    stateName: json["state_name"],
    stateId: json["state_id"],
    nightCharge: json["night_charge"],
    todayCharge: json["today_charge"],
    noOfHours: json["no_of_hours"],
    noOfDays: json["no_of_days"],
    bookBy: json["book_by"],
    operatorId: json["operator_id"],
    signingCode: json["signing_code"],
    notify: json["notify"],
    cardSelectStatus: json["card_select_status"],
    cancelReaison: json["cancel_reaison"],
    rushCharge: json["rush_charge"],
    weekend: json["weekend"],
    witness: json["witness"],
    express: json["express"],
    estimateTime: json["estimate_time"],
    estimateDistance: json["estimate_distance"],
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "user_id": userId,
    "driver_id": driverId,
    "driver_ids": driverIds,
    "picuplocation": picuplocation,
    "dropofflocation": dropofflocation,
    "picuplat": picuplat,
    "pickuplon": pickuplon,
    "droplat": droplat,
    "droplon": droplon,
    "shareride_type": sharerideType,
    "booktype": booktype,
    "car_type_id": carTypeId,
    "car_seats": carSeats,
    "number_of_witness": numberOfWitness,
    "booked_seats": bookedSeats,
    "req_datetime": reqDatetime.toIso8601String(),
    "timezone": timezone,
    "picklatertime": picklatertime,
    "picklaterdate": picklaterdate.toIso8601String(),
    "route_img": routeImg,
    "start_time": startTime,
    "end_time": endTime,
    "wt_start_time": wtStartTime,
    "wt_end_time": wtEndTime,
    "waiting_status": waitingStatus,
    "accept_time": acceptTime,
    "waiting_cnt": waitingCnt,
    "type_of_signing_id": typeOfSigningId,
    "apply_code": applyCode,
    "payment_type": paymentType,
    "ride_fare": rideFare,
    "card_id": cardId,
    "status": status,
    "type_of_signing_name": typeOfSigningName,
    "company_id": companyId,
    "number_of_signing": numberOfSigning,
    "car_type_name": carTypeName,
    "realstate_signing": realstateSigning,
    "realstate_settlement": realstateSettlement,
    "location_type": locationType,
    "name": name,
    "mobile": mobile,
    "email": email,
    "payment_status": paymentStatus,
    "user_rating_status": userRatingStatus,
    "upload_document": uploadDocument,
    "emailtoprit": emailtoprit,
    "scanandemail": scanandemail,
    "prepaid": prepaid,
    "overnight": overnight,
    "state_name": stateName,
    "state_id": stateId,
    "night_charge": nightCharge,
    "today_charge": todayCharge,
    "no_of_hours": noOfHours,
    "no_of_days": noOfDays,
    "book_by": bookBy,
    "operator_id": operatorId,
    "signing_code": signingCode,
    "notify": notify,
    "card_select_status": cardSelectStatus,
    "cancel_reaison": cancelReaison,
    "rush_charge": rushCharge,
    "weekend": weekend,
    "witness": witness,
    "express": express,
    "estimate_time": estimateTime,
    "estimate_distance": estimateDistance,
  };
}
